config/routes.rb
# frozen_string_literal: true

Stenographer::Engine.routes.draw do
  resources :links
  resources :changes, only: %i[index show], constraints: Stenographer::RoutingConstraints::ViewerOnly.new
  resources :changes, only: %i[create] # Created separately because we don't want it behind the routing constraints

  scope '/admin' do
    get '/' => 'admin#index', as: :admin_index, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
  end

  namespace :admin do
    resources :authentications, only: %i[index show destroy], constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :changes, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :outputs, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :links, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
  end

  get '/auth/:provider', to: 'authentications#create', as: :authentication # Used so we can access authentication_path('provider')
  get '/auth/:provider/callback', to: 'authentications#create'
  get '/auth/failure', to: 'authentications#failure'

  root 'changes#index', constraints: Stenographer::RoutingConstraints::ViewerOnly.new
end

app/models/stenographer/change.rb
# frozen_string_literal: true

module Stenographer
  class Change < ApplicationRecord
    VALID_CHANGE_TYPES = Stenographer.change_types

    before_save :sanitize_environment
    after_commit :send_to_outputs, on: [:create]
    after_update :send_to_outputs, if: proc { |change| change.saved_change_to_environments? }

    validates :message, presence: true
    validates :change_type, inclusion: { in: VALID_CHANGE_TYPES }, allow_nil: true

    def sanitize_environment
      if environments.present?
        environments_array = environments.split(',').map do |environment|
          environment.downcase.strip
        end
        environments_array.uniq!
        environments_array.join(', ')
      end
    end

    def to_markdown(truncate: nil)
      msg = truncate ? message.truncate(truncate) : message
      Stenographer.markdown_renderer.render(msg).html_safe
    end

    def matches_filters(output = nil)
      return false if output.blank?

      filters = output.filters_hash
      return true if filters.empty?

      filters.none? do |key, value|
        if value.present? && key == :environments
          environments_array = environments.split(',').map(&:strip)
          environments_array.last != value.strip
        else
          value.present? && send(key) != value
        end
      end
    end

    def environments_to_tags
      tags = []

      environment_array = environments.split(',').map(&:strip)
      environment_array.each do |environment|
        tags << {
          name: environment.capitalize,
          color: environment == 'production' ? 'is-primary' : 'is-light'
        }
      end

      tags
    end

    def self.create_or_update_by_source_id(change_params)
      source_id = change_params[:source_id]

      if source_id.present? && (change = Change.find_by(source_id: source_id)).present?
        change.environments += ", #{change_params[:environments]}"
        change.save
      else
        Change.create(change_params)
      end
    end

    private

    def send_to_outputs
      unless Rails.env.test?
        Output.all.find_each do |output|
          if matches_filters(output)
            output_class = "Stenographer::Outputs::#{output.authentication.provider.classify}Output".constantize
            sender = output_class.new(output: output, change: self)
            sender.send
          end
        end
      end
    end
  end
end

app/controllers/stenographer/admin/changes_controller.rb
# frozen_string_literal: true

require_dependency 'stenographer/application_controller'

module Stenographer
  class Admin::ChangesController < ApplicationController
    before_action :assign_change, only: %i[show edit update destroy]

    def new
      @change = Change.new
    end

    def create
      @change = Change.new(change_params)
      @change.environments = Rails.env.to_s.downcase

      if @change.save
        redirect_to admin_change_path(@change), notice: 'Change Created'
      else
        flash.now[:alert] = @change.errors.full_messages.to_sentence
        render :new
      end
    end

    def index
      page = params[:page] || 1
      @changes = Change.order(created_at: :desc).paginate(page: page, per_page: Stenographer.per_page)
    end

    def show; end

    def edit; end

    def update
      message = {}

      if @change.update(change_params)
        message[:notice] = 'Change Updated'

        redirect_to admin_change_path(@change), message
      else
        flash.now[:alert] = @change.errors.full_messages.to_sentence
        render :edit
      end
    end

    def destroy
      if @change.destroy
        redirect_to admin_changes_path, notice: 'Change Destroyed'
      else
        redirect_to admin_change_path(@change), alert: @change.errors.full_messages.to_sentence
      end
    end

    private

    def change_params
      params.require(:change).permit(:created_at, :message, :visible, :change_type, :environments, :tracker_ids)
    end

    def assign_change
      @change = Change.find(params[:id])
    end
  end
end

app/controllers/stenographer/changes_controller.rb
# frozen_string_literal: true

require_dependency 'stenographer/application_controller'

module Stenographer
  class ChangesController < ApplicationController
    skip_before_action :verify_authenticity_token, only: %i[create]

    def create
      parser = Stenographer.parser.constantize.new

      parms = params.permit!
      changes = parser.parse(parms)
      changes.each do |change|
        Change.create_or_update_by_source_id(change)
      end

      head :ok
    end

    def index
      page = params[:page] || 1

      @change_count = Change.where(visible: true).count
      @changes = Change.where(visible: true)
                       .order(created_at: :desc)
                       .paginate(page: page, per_page: Stenographer.per_page)
    end

    def show
      @change = Change.find(params[:id])
    end
  end
end

app/helpers/stenographer/changes_helper.rb
# frozen_string_literal: true

module Stenographer
  module ChangesHelper
  end
end

app/views/stenographer/admin/changes/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Edit Change #<%= @change.id %>
    </h1>

    <h2 class="subtitle">
      <%= link_to 'Show', admin_change_path(@change.id) %>
      |
      <%= link_to 'Delete', admin_change_path(@change), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this Change?' } %>
    </h2>

    <%= form_for @change, url: admin_change_path(@change), method: :patch do |f| %>
      <div class="field">
        <%= f.label :created_at, 'Date', class: 'label' %>
        <div class="control">
          <%= f.date_select(:created_at, { :order => [:month, :day, :year] }, { class: 'select' }) %>
        </div>
      </div>

      <div class="field">
        <%= f.label :message, class: 'label' %>
        <div class="control">
          <%= f.text_area :message, rows: 5, class: 'textarea' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.label :visible, class: 'label' %>
          <%= f.check_box :visible %>
        </div>
      </div>

      <div class="field">
        <%= f.label :change_type, class: 'label' %>
        <div class="control">
          <div class="select">
            <%= f.select :change_type, Stenographer::Change::VALID_CHANGE_TYPES, {} %>
          </div>
        </div>
      </div>

      <div class="field">
        <%= f.label :environments, 'Environments (comma separated)', class: 'label' %>
        <div class="control">
          <%= f.text_field :environments, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <%= f.label :tracker_ids, 'Tracker IDs (comma separated)', class: 'label' %>
        <div class="control">
          <%= f.text_field :tracker_ids, class: 'input' %>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= f.submit 'Update Change', class: 'button is-link' %>
        </div>
        <div class="control">
          <%= link_to('Back', admin_change_path(@change.id), class: 'button is-text') %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/stenographer/admin/changes/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Changes Admin
    </h1>

    <h2 class="subtitle">
      <%= link_to 'New Change', new_admin_change_path %>
    </h2>

    <table class="table is-fullwidth is-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>Date</th>
          <th>Message</th>
          <th>Visible</th>
          <th>Type</th>
          <th>Environments</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @changes.each do |change| %>
        <tr>
          <td><%= link_to(change.id, admin_change_path(change.id)) %></td>
          <td><%= change.created_at.strftime('%Y/%m/%d') %></td>
          <td title="<%= change.message %>"><%= change.to_markdown(truncate: 80) %></td>
          <td><%= change.visible.to_s %></td>
          <td><%= change.change_type.present? ? change.change_type.titleize : 'General'%></td>
          <td>
            <%= render partial: 'stenographer/shared/tags', locals: { tags: change.environments_to_tags } %>
          </td>
          <td>
            <%= link_to 'View', admin_change_path(change.id), class: 'button is-small' %>
            <%= link_to 'Edit', edit_admin_change_path(change.id), class: 'button is-small' %>
            <%= link_to 'Delete', admin_change_path(change.id), class: 'button is-small is-danger', :method => :delete, :data => {:confirm => 'Are you sure you want to delete this Change?'} %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="changes-pagination">
      <%= will_paginate @changes, renderer: BulmaPagination::Rails %>
    </div>
  </div>
</section>

app/views/stenographer/admin/changes/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Admin New Change
    </h1>

    <%= form_for @change, url: admin_changes_path(@change), method: :post do |f| %>
      <div class="field">
        <%= f.label :created_at, 'Date', class: 'label' %>
        <div class="control">
          <%= f.date_select(:created_at, :order => [:month, :day, :year]) %>
        </div>
      </div>

      <div class="field">
        <%= f.label :message, class: 'label' %>
        <div class="control">
          <%= f.text_area :message, rows: 5, class: 'textarea' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.label :visible, class: 'label' %>
          <%= f.check_box :visible %>
        </div>
      </div>

      <div class="field">
        <%= f.label :change_type, class: 'label' %>
        <div class="control">
          <div class="select">
            <%= f.select :change_type, Stenographer::Change::VALID_CHANGE_TYPES, {} %>
          </div>
        </div>
      </div>

      <div class="field">
        <%= f.label :tracker_ids, class: 'label' %>
        <div class="control">
          <%= f.text_field :tracker_ids, class: 'input' %>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= f.submit 'Create Change', class: 'button is-link' %>
        </div>
        <div class="control">
          <%= link_to('Back', admin_changes_path, class: 'button is-text') %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/stenographer/admin/changes/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Change #<%= @change.id %>
    </h1>

    <h2 class="subtitle">
      <%= link_to 'Edit', edit_admin_change_path(@change.id) %>
      |
      <%= link_to 'Delete', admin_change_path(@change), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this Change?' } %>
    </h2>

    <div class="field">
      <label class="label">Date</label>
      <div><%= @change.created_at.strftime('%m/%d/%Y') %></div>
    </div>

    <div class="field">
      <label class="label">Message</label>
      <div><%= @change.to_markdown %></div>
    </div>

    <div class="field">
      <label class="label">Source ID</label>
      <div><%= @change.source_id %></div>
    </div>

    <div class="field">
      <label class="label">Type</label>
      <div>
        <%= @change.change_type.present? ? @change.change_type.titleize : 'General' %>
      </div>
    </div>

    <div class="field">
      <label class="label">Environments</label>
      <div>
        <%= render partial: 'stenographer/shared/tags', locals: { tags: @change.environments_to_tags } %>
      </div>
    </div>

    <div class="field">
      <label class="label">Tracker IDs</label>
      <div>
        <% if @change.tracker_ids.present? %>
          <% @change.tracker_ids.split(',').each do |tracker_id| %>
            <%= tracker_id %>
          <% end %>
        <% else %>
          -
        <% end %>
      </div>
    </div>

    <div class="field">
      <%= link_to('Back', admin_changes_path, class: 'button is-link') %>
    </div>
  </div>
</section>