config/routes.rb
# frozen_string_literal: true

Stenographer::Engine.routes.draw do
  resources :links
  resources :changes, only: %i[index show], constraints: Stenographer::RoutingConstraints::ViewerOnly.new
  resources :changes, only: %i[create] # Created separately because we don't want it behind the routing constraints

  scope '/admin' do
    get '/' => 'admin#index', as: :admin_index, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
  end

  namespace :admin do
    resources :authentications, only: %i[index show destroy], constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :changes, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :outputs, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :links, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
  end

  get '/auth/:provider', to: 'authentications#create', as: :authentication # Used so we can access authentication_path('provider')
  get '/auth/:provider/callback', to: 'authentications#create'
  get '/auth/failure', to: 'authentications#failure'

  root 'changes#index', constraints: Stenographer::RoutingConstraints::ViewerOnly.new
end

app/models/stenographer/output.rb
# frozen_string_literal: true

module Stenographer
  class Output < ApplicationRecord
    validates :authentication_id, presence: true
    validates :configuration, presence: true

    belongs_to :authentication, class_name: 'Stenographer::Authentication'

    def configuration_hash
      configuration.present? ? JSON.parse(configuration, symbolize_names: true) : {}
    end

    def filters_hash
      filters.present? ? JSON.parse(filters, symbolize_names: true) : {}
    end

    def provider
      authentication.provider
    end
  end
end

app/controllers/stenographer/admin/outputs_controller.rb
# frozen_string_literal: true

require_dependency 'stenographer/application_controller'

module Stenographer
  class Admin::OutputsController < ApplicationController
    include Stenographer::OutputsHelper

    before_action :assign_output, only: %i[show edit update destroy]

    def index
      @authentication_count = Authentication.count
      @providers = Authentication.providers

      page = params[:page] || 1
      @outputs = Output.order(id: :desc).paginate(page: page, per_page: Stenographer.per_page)
    end

    def show; end

    def new
      authentication_id = params[:output][:authentication_id]
      @authentication = Authentication.find_by(id: authentication_id)

      if @authentication.present?
        @output = Output.new(authentication_id: authentication_id)
      else
        redirect_to admin_outputs_path, alert: 'Cannot create an Output without a Provider'
      end
    end

    def create
      @output = Output.new(output_params)
      @output.configuration = params[:configuration].to_json
      @output.filters = params[:filters].to_json

      if @output.save
        redirect_to admin_output_path(@output), notice: 'Output Created'
      else
        redirect_to admin_outputs_path, alert: @output.errors.full_messages.to_sentence
      end
    end

    def edit
      @authentication = @output.authentication
    end

    def update
      @output.configuration = params[:configuration].to_json
      @output.filters = params[:filters].to_json

      if @output.save
        redirect_to admin_output_path(@output), notice: 'Output Created'
      else
        redirect_to admin_outputs_path, alert: @output.errors.full_messages.to_sentence
      end
    end

    def destroy
      if @output.destroy
        redirect_to admin_outputs_path, notice: 'Output Destroyed'
      else
        redirect_to admin_output_path(@output), alert: @output.errors.full_messages.to_sentence
      end
    end

    private

    def assign_output
      @output = Output.find(params[:id])
    end

    def output_params
      params.require(:output).permit(:authentication_id)
    end
  end
end

app/helpers/stenographer/outputs_helper.rb
# frozen_string_literal: true

module Stenographer
  module OutputsHelper
    def slack_channels(output)
      slack_output = Stenographer::Outputs::SlackOutput.new(output: output)
      slack_output.channels
    end
  end
end

app/views/stenographer/admin/outputs/_filters.html.erb
<% filters = @output.filters_hash %>
<% change_type_selected = filters[:change_type] %>
<% environment_selected = filters[:environments] %>

<br />
<h2 class="subtitle">Filters</h2>

<div class="field">
  <%= label_tag :change_type, 'Change Type (optional)', class: 'label' %>
  <div class="control">
    <div class="select">
      <%= select('filters', 'change_type', Stenographer::Change::VALID_CHANGE_TYPES, { selected: change_type_selected, include_blank: true }) %>
    </div>
  </div>
</div>

<div class="field">
  <%= label_tag :environments, 'Environments (optional, csv)', class: 'label' %>
  <div class="control">
    <%= text_field_tag 'filters[environments]', environment_selected, class: 'input' %>
  </div>
</div>

app/views/stenographer/admin/outputs/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Edit Output #<%= @output.id %>
    </h1>

    <h2 class="subtitle">
      <%= link_to 'Show', admin_output_path(@output.id) %>
      |
      <%= link_to 'Delete', admin_output_path(@output), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this Output?' } %>
    </h2>

    <%= form_for @output, url: admin_output_path(@output), method: :patch do |f| %>
      <%= render partial: "stenographer/admin/outputs/providers/#{@authentication.provider}", cache: true %>
      <%= render partial: "stenographer/admin/outputs/filters" %>
      <div class="field is-grouped">
        <div class="control">
          <%= f.submit 'Update Output', class: 'button is-link' %>
        </div>
        <div class="control">
          <%= link_to('Back', admin_output_path(@output.id), class: 'button is-text') %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/stenographer/admin/outputs/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Outputs Admin
    </h1>

    <%- if @authentication_count.positive? %>
      <h2 class="subtitle">
        <%= form_tag new_admin_output_path, method: :get do |f| %>
          <div class="field has-addons">
            <div class="control">
              <div class="select">
                <%= select('output', 'authentication_id', Stenographer::Authentication.all.collect {|p| [ p.provider.titleize, p.id ] }) %>
              </div>
            </div>
            <div class="control">
              <%= submit_tag 'New Output', class: 'button is-link' %>
            </div>
          </div>
        <% end %>
      </h2>

      <table class="table is-fullwidth is-striped">
        <thead>
          <tr>
            <th>ID</th>
            <th>Authentication Provider</th>
            <th>Configuration</th>
            <th>Filters</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
        <% @outputs.each do |output| %>
          <tr>
            <td><%= link_to(output.id, admin_output_path(output.id)) %></td>
            <td><%= output.authentication.provider.titleize %></td>
            <td><%= render partial: 'stenographer/shared/key_value_row_display', locals: { dictionary: output.configuration_hash } %></td>
            <td><%= render partial: 'stenographer/shared/key_value_row_display', locals: { dictionary: output.filters_hash } %></td>
            <td>
              <%= link_to 'View', admin_output_path(output.id), class: 'button is-small' %>
              <%= link_to 'Edit', edit_admin_output_path(output.id), class: 'button is-small' %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>

          <div class="changes-pagination">
            <%= will_paginate @outputs, renderer: BulmaPagination::Rails %>
          </div>
    <% else %>
      <div class="notification is-warning">
        <label class="label">Output Help:</label>
        Please setup an Authentication first in order to setup an output.
      </div>
    <% end %>
  </div>
</section>

app/views/stenographer/admin/outputs/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      New Output
    </h1>

    <h2 class="subtitle"><%= @authentication.provider.titleize %></h2>
    <%= form_for @output, url: admin_outputs_path(@output), method: :post do |f| %>
      <%= f.hidden_field :authentication_id, value: @authentication.id %>
      <%= render partial: "stenographer/admin/outputs/providers/#{@authentication.provider}", cache: true %>
      <%= render partial: "stenographer/admin/outputs/filters" %>
      <div class="field is-grouped">
        <div class="control">
          <%= f.submit 'Create Output', class: 'button is-link' %>
        </div>
        <div class="control">
          <%= link_to('Back', admin_outputs_path, class: 'button is-text') %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/stenographer/admin/outputs/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Output #<%= @output.id %>
    </h1>

    <h2 class="subtitle">
      <%= link_to 'Edit', edit_admin_output_path(@output.id) %>
      |
      <%= link_to 'Delete', admin_output_path(@output), :method => :delete, :data => {:confirm => 'Are you sure you want to delete this Output?'} %>
    </h2>

    <div class="field">
      <label class="label">Date</label>
      <div><%= @output.created_at.strftime('%m/%d/%Y') %></div>
    </div>

    <div class="field">
      <label class="label">Authentication Provider</label>
      <div><%= link_to @output.authentication.provider.titleize, admin_authentication_path(@output.authentication.id) %></div>
    </div>

    <br />
    <h2 class="title is-4">Configuration</h2>
    <%= render partial: 'stenographer/shared/key_value_field_display', locals: { dictionary: @output.configuration_hash } %>

    <br />
    <h2 class="title is-4">Filters</h2>
    <%= render partial: 'stenographer/shared/key_value_field_display', locals: { dictionary: @output.filters_hash } %>

    <div class="field">
      <%= link_to('Back', admin_outputs_path, class: 'button is-link') %>
    </div>
  </div>
</section>