config/routes.rb
# frozen_string_literal: true

Stenographer::Engine.routes.draw do
  resources :links
  resources :changes, only: %i[index show], constraints: Stenographer::RoutingConstraints::ViewerOnly.new
  resources :changes, only: %i[create] # Created separately because we don't want it behind the routing constraints

  scope '/admin' do
    get '/' => 'admin#index', as: :admin_index, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
  end

  namespace :admin do
    resources :authentications, only: %i[index show destroy], constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :changes, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :outputs, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
    resources :links, constraints: Stenographer::RoutingConstraints::ManagerOnly.new
  end

  get '/auth/:provider', to: 'authentications#create', as: :authentication # Used so we can access authentication_path('provider')
  get '/auth/:provider/callback', to: 'authentications#create'
  get '/auth/failure', to: 'authentications#failure'

  root 'changes#index', constraints: Stenographer::RoutingConstraints::ViewerOnly.new
end

app/models/stenographer/link.rb
# frozen_string_literal: true

module Stenographer
  class Link < ApplicationRecord
    validates :url, presence: true
  end
end

app/controllers/stenographer/admin/links_controller.rb
# frozen_string_literal: true

require_dependency 'stenographer/application_controller'

module Stenographer
  class Admin::LinksController < ApplicationController
    before_action :assign_link, only: %i[show edit update destroy]

    def new
      @link = Link.new
    end

    def create
      @link = Link.new(link_params)

      if @link.save
        redirect_to admin_link_path(@link), notice: 'Link Created'
      else
        flash.now[:alert] = @link.errors.full_messages.to_sentence
        render :new
      end
    end

    def index
      page = params[:page] || 1
      @links = Link.order(created_at: :desc).paginate(page: page, per_page: Stenographer.per_page)
    end

    def show; end

    def edit; end

    def update
      message = {}

      if @link.update(link_params)
        message[:notice] = 'Link Updated'

        redirect_to admin_link_path(@link), message
      else
        flash.now[:alert] = @link.errors.full_messages.to_sentence
        render :edit
      end
    end

    def destroy
      if @link.destroy
        redirect_to admin_links_path, notice: 'Link Destroyed'
      else
        redirect_to admin_link_path(@link), alert: @link.errors.full_messages.to_sentence
      end
    end

    private

    def link_params
      params.require(:link).permit(:url, :description)
    end

    def assign_link
      @link = Link.find(params[:id])
    end
  end
end

app/views/stenographer/admin/links/edit.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Edit Link #<%= @link.id %>
    </h1>

    <h2 class="subtitle">
      <%= link_to 'Show', admin_link_path(@link.id) %>
      |
      <%= link_to 'Delete', admin_link_path(@link), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this Link?' } %>
    </h2>

    <%= form_for @link, url: admin_link_path(@link), method: :patch do |f| %>
      <div class="field">
        <div class="control">
          <%= f.label :url, class: 'label' %>
          <%= f.text_field :url, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.label :description, class: 'label' %>
          <%= f.text_field :description, class: 'input' %>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= f.submit 'Update Link', class: 'button is-link' %>
        </div>
        <div class="control">
          <%= link_to('Back', admin_link_path(@link.id), class: 'button is-text') %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/stenographer/admin/links/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Link Admin
    </h1>

    <h2 class="subtitle">
      <%= link_to 'New Link', new_admin_link_path %>
    </h2>

    <table class="table is-fullwidth is-striped">
      <thead>
        <tr>
          <th>ID</th>
          <th>URL</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link_to(link.id, admin_link_path(link.id)) %></td>
          <td><%= link.url %></td>
          <td>
            <%= link_to 'View', admin_link_path(link.id), class: 'button is-small' %>
            <%= link_to 'Edit', edit_admin_link_path(link.id), class: 'button is-small' %>
            <%= link_to 'Delete', admin_link_path(link.id), class: 'button is-small is-danger', :method => :delete, :data => {:confirm => 'Are you sure you want to delete this Change?'} %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="changes-pagination">
      <%= will_paginate @links, renderer: BulmaPagination::Rails %>
    </div>
  </div>
</section>

app/views/stenographer/admin/links/new.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Admin New Link
    </h1>

    <%= form_for @link, url: admin_links_path(@link), method: :post do |f| %>
      <div class="field">
        <div class="control">
          <%= f.label :url, class: 'label' %>
          <%= f.text_field :url, class: 'input' %>
        </div>
      </div>

      <div class="field">
        <div class="control">
          <%= f.label :description, class: 'label' %>
          <%= f.text_field :description, class: 'input' %>
        </div>
      </div>

      <div class="field is-grouped">
        <div class="control">
          <%= f.submit 'Create Link', class: 'button is-link' %>
        </div>
        <div class="control">
          <%= link_to('Back', admin_links_path, class: 'button is-text') %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/stenographer/admin/links/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Link #<%= @link.id %>
    </h1>

    <h2 class="subtitle">
      <%= link_to 'Edit', edit_admin_link_path(@link.id) %>
      |
      <%= link_to 'Delete', admin_link_path(@link), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this Link?' } %>
    </h2>

    <div class="field">
      <label class="label">Date</label>
      <div><%= @link.created_at.strftime('%m/%d/%Y') %></div>
    </div>

    <div class="field">
      <label class="label">URL</label>
      <div><%= @link.url %></div>
    </div>

    <div class="field">
      <label class="label">Description</label>
      <div><%= @link.description %></div>
    </div>

    <div class="field">
      <%= link_to('Back', admin_links_path, class: 'button is-link') %>
    </div>
  </div>
</section>